site_name: Starboard
site_url: https://aquasecurity.github.io/starboard/
site_description: Kubernetes-native security toolkit
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/aquasecurity/starboard
edit_uri: ""

nav:
  - Introduction: index.md
  - Starboard CLI:
      - Overview: cli/index.md
      - Installation:
          - From the Binary Releases: cli/installation/binary-releases.md
          - Krew: cli/installation/krew.md
          - Docker: cli/installation/docker.md
          - From Source (Linux, macOS): cli/installation/source.md
      - Getting Started: cli/getting-started.md
  - Starboard Operator:
      - Overview: operator/index.md
      - Installation:
          - kubectl: operator/installation/kubectl.md
          - Helm: operator/installation/helm.md
          - Operator Lifecycle Manager: operator/installation/olm.md
      - Getting Started: operator/getting-started.md
      - Configuration: operator/configuration.md
  - Configuration: configuration.md
  - Integrations:
      - Vulnerability Scanners:
          - Overview: integrations/vulnerability-scanners/index.md
          - Trivy: integrations/vulnerability-scanners/trivy.md
          - Aqua Enterprise: integrations/vulnerability-scanners/aqua-enterprise.md
      - Private Registries: integrations/private-registries.md
      - Managed Registries: integrations/managed-registries.md
      - Octant Plugin: integrations/octant.md
      - Lens Extension: integrations/lens.md
  - Custom Resource Definitions: crds.md
  - Frequently Asked Questions: faq.md
  - Troubleshooting: troubleshooting.md

theme:
  name: material
  highlightjs: true
  language: 'en'
