name: Publish Chart Helm
on:
  pull_request:
  workflow_dispatch:
jobs:
  lint-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Create kind cluster
        uses: helm/kind-action@v1.1.0

      - name: Run chart-testing lint-install
        run: ct lint-and-install --chart-dirs deploy --validate-maintainers=false

  release:
    runs-on: ubuntu-20.04
    needs:
      - lint-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.0
      - name: Install chart-releaser
        run: |
          wget https://github.com/helm/chart-releaser/releases/download/v1.1.1/chart-releaser_1.1.1_linux_amd64.tar.gz
          tar xzvf chart-releaser_1.1.1_linux_amd64.tar.gz cr
      - name: Package Upload helm chart
        continue-on-error: true
        run: |
          ./cr package deploy/helm
          ./cr upload -o krolval -r helm-charts -p . --token ${{ secrets.HELM_REP_TOKEN }} -p .cr-release-packages
          ./cr index -o krolval -r helm-charts -c https://krolval.github.io/helm-charts/ -i index.yaml
          mkdir output && mv index.yaml output
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.HELM_REP_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: 'krolval'
          destination-repository-name: 'helm-charts'
          user-email: ci@aquasec.com